language: python

os:
  - linux
  - osx
  - windows

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements-dev.txt
  - pip install .

script:
  - flake8 pyss3
  - pytest tests/
